import{a as d,S as m,i as n}from"./assets/vendor-I-4NK6U0.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();function f(s){if(s)return d.get("https://pixabay.com/api/",{params:{key:"14797936-c0ac273b2bc1360021fe4ee91",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(r=>r.data.hits).catch(r=>{console.log(r)})}let p=new m(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"});const l=document.querySelector(".gallery"),c=document.querySelector(".loader");function g(s){const r=s.map(t=>`<li>
        <a href="${t.largeImageURL}">
        <img src="${t.webformatURL}" alt="${t.tags}" width="360">
        </a>
        <p>Likes<br/>${t.likes}</p>
        <p>Views<br/>${t.views}</p>
        <p>Comments<br/>${t.comments}</p>
        <p>Downloads<br/>${t.downloads}</p>
        </li>`).join("");l.innerHTML=r,p.refresh()}function h(){l.innerHTML=""}function y(){c.classList.remove("hidden")}function L(){c.classList.add("hidden")}const u=document.querySelector(".form");u.querySelectorAll("a");u.addEventListener("submit",s=>{s.preventDefault();const r=s.target.elements["search-text"];r.value===""&&n.show({color:"red",position:"topRight",message:"Please type in something"}),h(),y(),f(r.value).then(t=>{t.length===0?n.show({color:"red",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}):g(t)}).catch(t=>{n.show({color:"red",position:"topRight",message:t.message})}).finally(()=>{L()})});
//# sourceMappingURL=index.js.map
